import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text x=%2250%%22 y=%2250%%22 style=%22dominant-baseline:central;text-anchor:middle;font-size:90px;%22>🦌</text></svg>"
        ></link>
      </Head>
      <main>
        <h1>TOP</h1>
      </main>
    </>
  );
}
